dataset:
  data_path: ./data/train.json
  processed_train_path: ./processed_data/processed_train.csv
  processed_test_path: ./processed_data/processed_test.csv
  train_percentage: 0.8
  max_length: 1024
  random_seed: 1234
  bsz: 8
  is_shuffle: True
  down_sample_percentage: 0.3
model:
  base_model_name_or_path: "microsoft/deberta-v3-base"
  save_model_path: "./model"
trainer:
  output_dir: "./results"
  num_train_epochs: 3
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  weight_decay: 0.01
  logging_dir: './logs'
  evaluation_strategy: 'steps'
  logging_steps: 100
  eval_steps: 100
  